services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: hello_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: hello_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello_user -d hello_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hello_app_fastapi
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
      - .:/app

    # Overrides the Dockerfile's CMD for development
    # Runs uvicorn with the --reload flag
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data: