apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration-job
  namespace: birthday-app-ns
  labels:
    app: birthday-app
    task: db-migration
spec:
  # --- Job Configuration ---
  template:
    metadata:
      labels:
        app: birthday-app
        task: db-migration
    spec:
      serviceAccountName: birthday-app-sa
      shareProcessNamespace: true
      # --- Containers ---
      containers:
        # 1. Main container to run the Alembic command
        - name: alembic-migrate
          image: __FULL_IMAGE_PATH__
          # Override the default command to run Alembic instead of Uvicorn
          # command: ["alembic"]
          # args: ["upgrade", "head"]
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting migration..."
              # Run alembic and capture exit code
              alembic upgrade head
              ALEMBIC_EXIT_CODE=$?
              echo "Alembic finished with exit code $ALEMBIC_EXIT_CODE"

              # Find and terminate the proxy process
              echo "Terminate cloud-sql-proxy..."
              PROXY_PID=$(ps aux | grep cloud_sql_proxy | grep -v grep | awk '{print $1}')

              if [ -n "$PROXY_PID" ]; then
                echo "Found proxy PID: $PROXY_PID. Sending SIGTERM..."
                kill -TERM $PROXY_PID
                # Wait a moment for graceful shutdown
                sleep 5
              else
                echo "Proxy PID not found."
              fi

              echo "Exiting migration container."
              exit $ALEMBIC_EXIT_CODE

          env:
          # Read DB config from ConfigMap
          - name: DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: birthday-app-config
                key: DATABASE_USER
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: birthday-app-config
                key: DATABASE_NAME
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: birthday-app-config
                key: DATABASE_URL
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: birthday-app-config
                key: DATABASE_PORT
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

        # 2. Cloud SQL Proxy Sidecar (identical to the one in deployment.yaml)
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
          args:
            - "--structured-logs"
            - "--private-ip"
            - "--auto-iam-authn"
            - "--quit-on-zero-connections"
            - "$(SQL_INSTANCE_CONNECTION_NAME)"
          env:
          - name: SQL_INSTANCE_CONNECTION_NAME
            valueFrom:
              configMapKeyRef:
                name: birthday-app-config
                key: SQL_INSTANCE_CONNECTION_NAME
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

      restartPolicy: OnFailure

  backoffLimit: 2
  ttlSecondsAfterFinished: 3600 #clean up after 1 hour

